FROM node:14
RUN npm install pm2 -g;

# Key for copy source code
COPY --chmod=600 .jenkins/git/ssh_config /root/.ssh/config
COPY --chmod=600 .jenkins/git/git_rsa /root/.ssh/git_rsa

WORKDIR /usr/src/app
COPY . .
RUN yarn install

# Patch pwa
RUN sh patch.sh
EXPOSE 3000