module.exports = {
    collectCoverageFrom: [
        '**/(.*)$.{js,jsx,ts,tsx}',
        '!**/(.*)$.d.ts',
        '!**/node_modules/(.*)$*',
    ],
    moduleNameMapper: {
        // Handle CSS imports (with CSS modules)
        // https://jestjs.io/docs/webpack#mocking-css-modules
        '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',

        // Handle CSS imports (without CSS modules)
        '^.+\\.(css|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',

        // Handle image imports
        // https://jestjs.io/docs/webpack#handling-static-assets
        '^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$/i': '<rootDir>/__mocks__/fileMock.js',

        // Handle module aliases
        '^@root/(.*)$': '<rootDir>/$1',
        '^@pages/(.*)$': '<rootDir>/pages/$1',
        '^@custom/(.*)$': '<rootDir>/src/custom/$1',
        '^@config': '<rootDir>/swift.config.js',
        '^@core_modules/(.*)$': '<rootDir>/core/modules/$1',
        '^@core/(.*)$': '<rootDir>/core/$1',
        '^@core_minicart': '<rootDir>/core/modules/cart/plugins/mini',
        '^@module_checkout/(.*)$': '<rootDir>/core/modules/checkout/$1',

        '^@middlewares/(.*)$': '<rootDir>/core/middlewares/$1',
        '^@middleware_route': '<rootDir>/core/middlewares/route',

        '^@services/(.*)$': '<rootDir>/core/services/$1',
        '^@extension': '<rootDir>/extension/$1',
        '^@extension_module': '<rootDir>/extension/modules/$1',
        '^@next_headcustom': '<rootDir>/core/nextjs_custom/HeadCustom',
        '^@next_nextscriptcustom': '<rootDir>/core/nextjs_custom/NextScriptCustom',
        '^@graphql_request': '<rootDir>/core/api/graphql/request',

        '^@lib/(.*)$': '<rootDir>/core/lib/$1',
        '^@lib_apollo': '<rootDir>/core/lib/apollo',
        '^@lib_gtag': '<rootDir>/core/lib/gtag',
        '^@lib_firebase/(.*)$': '<rootDir>/core/lib/firebase/$1',
        '^@i18n': '<rootDir>/core/lib/i18n',

        '^@layout': '<rootDir>/core/modules/theme/layout',
        '^@layout/(.*)$': '<rootDir>/core/modules/theme/layout/$1',
        '^@layout_customer': '<rootDir>/core/modules/customer/components/layout',
        '^@layout_customer/(.*)$': '<rootDir>/core/modules/customer/components/layout/$1',

        '^@theme/(.*)$': '<rootDir>/core/theme/$1',
        '^@theme_color': '<rootDir>/core/theme/colors',
        '^@theme_mixins': '<rootDir>/core/theme/mixins',
        '^@theme_theme': '<rootDir>/core/theme/theme',
        '^@theme_typography': '<rootDir>/core/theme/typography',
        '^@theme_vars': '<rootDir>/core/theme/vars',

        '^@helpers/(.*)$': '<rootDir>/core/helpers/$1',
        '^@helper_auth': '<rootDir>/core/helpers/auth',
        '^@helper_cartid': '<rootDir>/core/helpers/cartId',
        '^@helper_checkcomponents': '<rootDir>/core/helpers/checkComponent',
        '^@helper_checkimagesrc': '<rootDir>/core/helpers/checkImageSrc',
        '^@helper_config': '<rootDir>/core/helpers/config',
        '^@helper_cookies': '<rootDir>/core/helpers/cookies',
        '^@helper_currency': '<rootDir>/core/helpers/currency',
        '^@helper_date': '<rootDir>/core/helpers/date',
        '^@helper_encryption': '<rootDir>/core/helpers/encryption',
        '^@helper_fonts': '<rootDir>/core/helpers/fonts',
        '^@helper_generatequery': '<rootDir>/core/helpers/generateQuery',
        '^@helper_getpath': '<rootDir>/core/helpers/getPath',
        '^@helper_noreload': '<rootDir>/core/helpers/noReload',
        '^@helper_passwordstrength': '<rootDir>/core/helpers/passwordStrength',
        '^@helper_productbyvariant': '<rootDir>/core/helpers/productByVariant',
        '^@helper_regex': '<rootDir>/core/helpers/regex',
        '^@helper_text': '<rootDir>/core/helpers/text',
        '^@helper_theme': '<rootDir>/core/helpers/theme',
        '^@helper_urlparser': '<rootDir>/core/helpers/urlParser',
        '^@helper_zxcvbn': '<rootDir>/core/helpers/zxcvbn',
        '^@helper_localstorage': '<rootDir>/core/helpers/localstorage',

        '^@common_button': '<rootDir>/core/modules/commons/Button',
        '^@common_buttonqty': '<rootDir>/core/modules/commons/ButtonQty',
        '^@common_breadcrumb': '<rootDir>/core/modules/commons/Breadcrumb',
        '^@common_confirmdialog': '<rootDir>/core/modules/commons/ConfirmDialog',
        '^@common_dropfile': '<rootDir>/core/modules/commons/DropFile',
        '^@common_googlemaps': '<rootDir>/core/modules/commons/GoogleMaps',
        '^@common_googlemaps_autocomplete': '<rootDir>/core/modules/commons/GoogleMapsAutocomplete',
        '^@common_gridlist': '<rootDir>/core/modules/commons/GridList',
        '^@common_priceformat': '<rootDir>/core/modules/commons/PriceFormat',
        '^@common_ratingstar': '<rootDir>/core/modules/commons/RatingStar',
        '^@common_tabs': '<rootDir>/core/modules/commons/Tabs',
        '^@common_toast': '<rootDir>/core/modules/commons/Toast',
        '^@common_typography': '<rootDir>/core/modules/commons/Typography',
        '^@common_checkbox': '<rootDir>/core/modules/commons/CheckBox',
        '^@common_password': '<rootDir>/core/modules/commons/Password',
        '^@common_radio': '<rootDir>/core/modules/commons/Radio',
        '^@common_rangeslider': '<rootDir>/core/modules/commons/RangeSlider',
        '^@common_select': '<rootDir>/core/modules/commons/Select',
        '^@common_textfield': '<rootDir>/core/modules/commons/TextField',
        '^@common_carousel': '<rootDir>/core/modules/commons/carousel',

        '^@common_button/(.*)$': '<rootDir>/core/modules/commons/Button/$1',
        '^@common_buttonqty/(.*)$': '<rootDir>/core/modules/commons/ButtonQty/$1',
        '^@common_breadcrumb/(.*)$': '<rootDir>/core/modules/commons/Breadcrumb/$1',
        '^@common_confirmdialog/(.*)$': '<rootDir>/core/modules/commons/ConfirmDialog/$1',
        '^@common_dropfile/(.*)$': '<rootDir>/core/modules/commons/DropFile/$1',
        '^@common_googlemaps/(.*)$': '<rootDir>/core/modules/commons/GoogleMaps/$1',
        '^@common_googlemaps_autocomplete/(.*)$': '<rootDir>/core/modules/commons/GoogleMapsAutocomplete/$1',
        '^@common_gridlist/(.*)$': '<rootDir>/core/modules/commons/GridList/$1',
        '^@common_priceformat/(.*)$': '<rootDir>/core/modules/commons/PriceFormat/$1',
        '^@common_ratingstar/(.*)$': '<rootDir>/core/modules/commons/RatingStar/$1',
        '^@common_tabs/(.*)$': '<rootDir>/core/modules/commons/Tabs/$1',
        '^@common_toast/(.*)$': '<rootDir>/core/modules/commons/Toast/$1',
        '^@common_typography/(.*)$': '<rootDir>/core/modules/commons/Typography/$1',
        '^@common_checkbox/(.*)$': '<rootDir>/core/modules/commons/CheckBox/$1',
        '^@common_password/(.*)$': '<rootDir>/core/modules/commons/Password/$1',
        '^@common_radio/(.*)$': '<rootDir>/core/modules/commons/Radio/$1',
        '^@common_rangeslider/(.*)$': '<rootDir>/core/modules/commons/RangeSlider/$1',
        '^@common_select/(.*)$': '<rootDir>/core/modules/commons/Select/$1',
        '^@common_textfield/(.*)$': '<rootDir>/core/modules/commons/TextField/$1',
        '^@common_carousel/(.*)$': '<rootDir>/core/modules/commons/carousel/$1',

        '^@common_image': '<rootDir>/core/modules/commons/Image',
        '^@common_image/(.*)$': '<rootDir>/core/modules/commons/Image/$1',

        '^@common_backdrop': '<rootDir>/core/modules/commons/Backdrop',
        '^@common_pageprogress': '<rootDir>/core/modules/commons/PageProgress',
        '^@common_backdrop/(.*)$': '<rootDir>/core/modules/commons/Backdrop/$1',
        '^@common_pageprogress/(.*)$': '<rootDir>/core/modules/commons/PageProgress/$1',
        '^@common_slick/(.*)$': '<rootDir>/core/modules/commons/Slick/$1',
        '^@common_slider/(.*)$': '<rootDir>/core/modules/commons/Slider/$1',
        '^@common_filterdialog': '<rootDir>/core/modules/commons/FilterDialog',
        '^@common_filterdialog/(.*)$': '<rootDir>/core/modules/commons/FilterDialog/$1',
        '^@common_forms/(.*)$': '<rootDir>/core/modules/commons/Forms/$1',

        '^@common_searchmodal': '<rootDir>/core/modules/commons/SearchModal',
        '^@common_loaders': '<rootDir>/core/modules/commons/Loaders',
        '^@common_searchmodal/(.*)$': '<rootDir>/core/modules/commons/SearchModal/$1',
        '^@common_loaders/(.*)$': '<rootDir>/core/modules/commons/Loaders/$1',

        '^@common_navigation': '<rootDir>/core/modules/commons/Navigation',
        '^@common_spancategory': '<rootDir>/core/modules/commons/SpanCategory',
        '^@common_span': '<rootDir>/core/modules/commons/Span',
        '^@common_skeleton': '<rootDir>/core/modules/commons/Skeleton',
        '^@common_scrolltotop': '<rootDir>/core/modules/commons/ScrollToTop',
        '^@common_headermobile': '<rootDir>/core/modules/theme/components/header/mobile',
        '^@common_headerdesktop': '<rootDir>/core/modules/theme/components/header/desktop',
        '^@common_restrictionPopup': '<rootDir>/core/modules/theme/components/restrictionPopup',
        '^@common_currency': '<rootDir>/core/modules/setting/components/currency',
        '^@common_language': '<rootDir>/core/modules/setting/components/language',
        '^@common_bottomnavigation': '<rootDir>/core/modules/theme/components/bottom-navigation/mobile',
        '^@common_footer': '<rootDir>/core/modules/theme/components/footer/desktop',
        '^@common_productlabel': '<rootDir>/core/modules/commons/ProductLabel',
        '^@common_optionconfigurable': '<rootDir>/core/modules/commons/OptionConfigurable',

        '^@common_navigation/(.*)$': '<rootDir>/core/modules/commons/Navigation/$1',
        '^@common_spancategory/(.*)$': '<rootDir>/core/modules/commons/SpanCategory/$1',
        '^@common_span/(.*)$': '<rootDir>/core/modules/commons/Span/$1',
        '^@common_skeleton/(.*)$': '<rootDir>/core/modules/commons/Skeleton/$1',
        '^@common_scrolltotop/(.*)$': '<rootDir>/core/modules/commons/ScrollToTop/$1',
        '^@common_headermobile/(.*)$': '<rootDir>/core/modules/theme/components/header/mobile/$1',
        '^@common_headerdesktop/(.*)$': '<rootDir>/core/modules/theme/components/header/desktop/$1',
        '^@common_restrictionPopup/(.*)$': '<rootDir>/core/modules/theme/components/restrictionPopup/$1',
        '^@common_currency/(.*)$': '<rootDir>/core/modules/setting/components/currency/$1',
        '^@common_language/(.*)$': '<rootDir>/core/modules/setting/components/language/$1',
        '^@common_bottomnavigation/(.*)$': '<rootDir>/core/modules/theme/components/bottom-navigation/mobile/$1',
        '^@common_footer/(.*)$': '<rootDir>/core/modules/theme/components/footer/desktop/$1',
        '^@common_productlabel/(.*)$': '<rootDir>/core/modules/commons/ProductLabel/$1',
        '^@common_optionconfigurable/(.*)$': '<rootDir>/core/modules/commons/OptionConfigurable/$1',

        '^@plugin_summary': '<rootDir>/core/modules/cart/plugins/Summary',
        '^@plugin_summary/(.*)$': '<rootDir>/core/modules/cart/plugins/Summary/$1',
        '^@plugin_shoppingbag': '<rootDir>/core/modules/cart/plugins/ShoppingBag',
        '^@plugin_shoppingbag/(.*)$': '<rootDir>/core/modules/cart/plugins/ShoppingBag/$1',
        '^@plugin_minicart': '<rootDir>/core/modules/cart/plugins/mini',
        '^@plugin_minicart/(.*)$': '<rootDir>/core/modules/cart/plugins/mini/$1',

        '^@plugin_gimmickbanner': '<rootDir>/core/modules/cart/plugins/GimmickBanner',
        '^@plugin_gimmickbanner/(.*)$': '<rootDir>/core/modules/cart/plugins/GimmickBanner/$1',

        '^@plugin_productlist': '<rootDir>/core/modules/catalog/plugins/ProductList',
        '^@plugin_productlist/(.*)$': '<rootDir>/core/modules/catalog/plugins/ProductList/$1',
        '^@plugin_productitem': '<rootDir>/core/modules/catalog/plugins/ProductItem',
        '^@plugin_productitem/(.*)$': '<rootDir>/core/modules/catalog/plugins/ProductItem/$1',

        '^@plugin_paypalbutton': '<rootDir>/core/modules/paypal/plugins/PaypalButton',
        '^@plugin_paypalbutton/(.*)$': '<rootDir>/core/modules/paypal/plugins/PaypalButton/$1',

        '^@plugin_addressform': '<rootDir>/core/modules/customer/plugins/AddressFormDialog',
        '^@plugin_addressform/(.*)$': '<rootDir>/core/modules/customer/plugins/AddressFormDialog/$1',
        '^@plugin_newsletter': '<rootDir>/core/modules/customer/plugins/Newsletter',
        '^@plugin_newsletter/(.*)$': '<rootDir>/core/modules/customer/plugins/Newsletter/$1',
        '^@plugin_otp': '<rootDir>/core/modules/login/plugins/otp',
        '^@plugin_otp/(.*)$': '<rootDir>/core/modules/login/plugins/otp/$1',
        '^@plugin_notificationbell': '<rootDir>/core/modules/notification/plugins/NotificationBell',
        '^@plugin_notificationbell/(.*)$': '<rootDir>/core/modules/notification/plugins/NotificationBell/$1',

        '^@plugin_optionitem': '<rootDir>/core/modules/product/plugins/OptionItem',
        '^@plugin_optionitem/(.*)$': '<rootDir>/core/modules/product/plugins/OptionItem/$1',
        '^@plugin_customizableitem': '<rootDir>/core/modules/product/plugins/CustomizableOption',
        '^@plugin_customizableitem/(.*)$': '<rootDir>/core/modules/product/plugins/CustomizableOption/$1',
        '^@plugin_rewardpointinfo': '<rootDir>/core/modules/rewardpoint/plugins/info',
        '^@plugin_rewardpointinfo/(.*)$': '<rootDir>/core/modules/rewardpoint/plugins/info/$1',

    },
    // Add more setup options before each test is run
    setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
    testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
    testEnvironment: 'jsdom',
    transform: {
        // Use babel-jest to transpile tests with the next/babel preset
        // https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object
        '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
    },
    transformIgnorePatterns: [
        '/node_modules/',
        '^.+\\.module\\.(css|sass|scss)$',
    ],
};
