export const SET_SELECT_CONFIGURABLE = 'SET_SELECT_CONFIGURABLE';
export const SET_SELECT_CONFIG_PRODUCT = 'SET_SELECT_CONFIG_PRODUCT';
export const SET_COUNT_REVIEW = 'SET_COUNT_REVIEW';

export default {
    SET_SELECT_CONFIGURABLE,
};
